### ISSUE TITLE
Ableton live 12 compatibility

### ISSUE THREAD

**Issue by rds2024-3004** [zsteinkamp/m4l-zs-Knobbler3#11]
Is this compatible with Live 12? I tested the latest version and it seems like it's not working.

**Comment by zsteinkamp** [comment]
Hi @rds2024-3004 -- I use it with Live 12. What problem are you seeing? Can you send more information?

**Comment by rds2024-3004** [comment]
I tried loading knobbler in an empty project of 11 and 12. In 12, nothing is mapping. I will try again tomorrow

**Comment by zsteinkamp** [comment]
Oftentimes clicking "Rescan Network" and ensuring your iPad (or wherever you are running TouchOSC) is selected can fix this problem, which is usually caused for me if I don't have the iPad ready with TouchOSC loaded prior to opening the Live Set. Click "Refresh" after selecting the iPad.

**Comment by rds2024-3004** [comment]
I tried it again in Live 12 and it's still not working on my end. Connection it properly setup and works perfectly in live 11

**Comment by rds2024-3004** [comment]
I just wanted to add. Using TouchOSC on desktop works fine on live 12

**Comment by rds2024-3004** [comment]
I tried this again and for it to work I will have to open this window. Once I close that window, the controls stop working again.

![image](https://github.com/user-attachments/assets/f8927670-f643-48a3-9234-9e9013611380)

**Comment by rds2024-3004** [comment]
Seems like I am able to fix the issue now. I just removed ableton in firewall then re-added it. Now sure what causes that issue. Thanks!

**Comment by zsteinkamp** [comment]
Glad you worked it out, @rds2024-3004. If the Windows firewall is similar to the Mac firewall, the firewall settings are done by application name, and whenever there's a big Live update, the application name changes from "Ableton Live Suite 11" to "Ableton Live Suite 12" and thus does not match the existing rules. I'm glad you figured it out!
