### ISSUE TITLE
Bluehand for Drift

### ISSUE THREAD

**Issue by DaWolfey** [zsteinkamp/m4l-zs-Knobbler3#3]
The new synth in Ableton 11.3 - Drift - does not appear in knobbler3 1.2.0 in the bluehand tab. It simply says no device detected when Drift is selected. Other instruments/effects work normally.

**Comment by zsteinkamp** [comment]
Thanks for the report, Darren! I was able to repro it here. Will update with info as I find it, but I suspect this is going to have to go to Ableton to get fixed in Drift. If that's the case, I'll file a ticket with them with a minimal repro case.

**Comment by zsteinkamp** [comment]
Seeing these errors in the Max console:
```
jsliveapi: 'DriftDevice' object has no attribute 'name'
jsliveapi: 'DriftDevice' object has no attribute 'parameters'
```
This is when the following code runs:
```
  data.observers.deviceName = new LiveAPI(deviceNameCallback, "live_set appointed_device");
  data.observers.deviceName.mode = 1;
  data.observers.deviceName.property = "name";

  data.observers.params = new LiveAPI(parametersCallback, "live_set appointed_device");
  data.observers.params.mode = 1;
  data.observers.params.property = "parameters";
```
I will send this info to Ableton support. Thanks again @DaWolfey!

**Comment by zsteinkamp** [comment]
Note sent to Ableton support.

**Comment by zsteinkamp** [comment]
The latest Live beta release notes for 11.3.10b1 lists "Users can now control Drift using Max for Live." in the change log.

**Comment by zsteinkamp** [comment]
Now working properly with the 11.3.10 release. :)
