### ISSUE TITLE
Bluehand device bank parameters

### ISSUE THREAD

**Issue by mrJonesmusic** [zsteinkamp/m4l-zs-Knobbler3#5]
Hello,

Firstly, thank you for this incredible work. I have a question and really hope that you can help me as i am scratching my head with this since several weeks....

Regarding your "Bluehand" touchOSC device, as i know, only the 16 first parameters of a device are mapped and I search a solution to be able to select the other banks of the device parameters so I could control all of the devices parameters that are available without the need to map them individually. As an exemple, my Launchpad pro mk3 can to this but as it doesn't has any screen it is really difficult to know in which order the device parameters are mapped.

Do you have any idea how I could implement this in your work? Is there any OSC message that exist in order to change the bank of parameter for the selected device?

Thanks in advance for your help_

**Comment by zsteinkamp** [comment]
Hey @mrJonesmusic -- First off, thanks for writing in with your situation and offer to help! 

I think this is an interesting idea to explore. Currently the code limits itself to the first 16 params (see `bluhand.js` line 9), but that is somewhat arbitrary and really only driven by how I was using it in Ableton. If I got into situations where device params were buried far down the list, I'd just group the device into a Rack and map the params I wanted from the device to the knobs in the rack, which then fits nicely with how Knobbler/Bluhand works. Not pretty, but it was a rare thing for me.

One note: OSC doesn't have predefined messages -- it's just a messaging format where you have full control over the sending and receiving side, so it's a matter of adding buttons to the TouchOSC layout that send messages like "prevBank" and "nextBank" and having code on the receiving side (the Max For Live device) to handle those messages properly.

I have some time this week to look at putting some Previous / Next bank buttons into the TouchOSC layout that send OSC messages to the Bluhand code to shift through banks of 16 params. To do this, I'd introduce a new variable into the code, e.g. `paramBank` and use that as an offset into the full set of params, with the loop in `bluhand.js` on line 133 making use of it, along with other protections around not letting the user move outside of the range of actual params.

Do you think it's important for it to remember which bank you were on when switching back and forth between devices? This would be a little more work, and could be done as a second step if having it always start with Bank 1 was annoying.

I think this would be pretty straightforward to do. Though if you'd like to take a crack at it, let me know. :) I think it would take me a couple of hours.

**Comment by mrJonesmusic** [comment]
Hey @zsteinkamp, thanks a lot for your fast reaction to my request !

I am still really at the beginning of understanding all the ins and outs of TouchOSC/MAX4Live/Javascript so I think That this could be taking me several month in order to achieve this :) 

So  it would be really fantastic if you could add these Previous / Next bank buttons ! And indeed, if you can make this that it remember which bank you were on when switching back and forth between devices, this could be a huge game changer for my way of working with Ableton Live  !

Again, thanks a lot for your precious help  ! ! ! You are really the best !

**Comment by zsteinkamp** [comment]
Happy to help :) Give this a try?
https://github.com/zsteinkamp/m4l-zs-Knobbler3/raw/main/frozen/zs-Knobbler3-1.3.0.zip
Make sure you also update the TouchOSC layout, since this one has next/prev bank buttons in the Bluhand tab.
Let me know how it goes...

**Comment by zsteinkamp** [comment]
(btw I didn't do the thing where it remembers the bank by device yet ... one step at a time)

**Comment by mrJonesmusic** [comment]
Your are a genius! It's working perfectly !!!!! Thanks a billion times for this!!! I am currently testing it intensively. One thing that I see is that the [CurrentParamKnob] isn't functioning anymore.

**Comment by mrJonesmusic** [comment]
There seems to be an issue with the value of parameters not appearing in BLuehand ( the value located at the upper side of each fade controls). I seems that TouchOSC is not getting them (3 dots are displayed instead) Does this is also the case from your side? Thanks again for your help!

**Comment by zsteinkamp** [comment]
Hey @mrJonesmusic it looks like I got a little ahead of myself and left a trail of bugs :) Try the latest one up now.
https://github.com/zsteinkamp/m4l-zs-Knobbler3/raw/main/frozen/zs-Knobbler3-1.3.1.zip

**Comment by mrJonesmusic** [comment]
Hey @zsteinkamp, thanks again for your work but it seems that the ZIP file that you uploaded got corrupted. I tried to re-download several times but when I try to open it i am getting an error message "impossible to open the file: data corrupted".

Thanks in advance for your help!

**Comment by zsteinkamp** [comment]
Very odd. I downloaded it and it worked fine here. Not sure about that one! 
I just uploaded an `.amxd` file directly, without the .zip. You will need to be sure to use the latest `.tosc` file in the repo root. https://github.com/zsteinkamp/m4l-zs-Knobbler3/raw/main/frozen/zs-Knobbler3-1.3.1.amxd

**Comment by mrJonesmusic** [comment]
Thanks again for all your work! It is working perfectly now! This is for me the ultimate Ableton devices controller!!!! Using this with a launchpad pro mk3 make this a perfect controller setup! Thanks a lot for this!

**Comment by zsteinkamp** [comment]
Glad to hear it :) Thanks for letting me know. Always happy to hear about problems or ideas for improvement!
